name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Setup Node.js 🏗
        uses: actions/setup-node@v2.5.3
        with:
          node-version: 16

      - name: Get yarn cache directory path 🛠
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV

      - name: Cache node_modules 📦
        uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: ubuntu-latest-yarn-${{ hashFiles('new-web/yarn.lock') }}

      - name: Install dependencies 👨🏻‍💻
        working-directory: new-web
        run: yarn install

      - name: Run linter 👀
        working-directory: new-web
        run: yarn lint

      - name: Run tests 🧪
        working-directory: new-web
        run: yarn test
