name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Setup Node.js and Yarn 🏗
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Yarn 📦
        run: npm install -g yarn

      - name: Change to new-web directory 📂
        run: cd open-etc-pool-friends/new-web

      - name: Install Dependencies 👨🏻‍💻
        run: yarn install

      - name: Lint and Fix ✨
        run: yarn lint-fix

      - name: Build 🏗
        run: yarn build

      - name: Test 🧪
        run: yarn test
