name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Setup Node.js 🏗
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get yarn cache directory path 🛠
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules 📦
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ubuntu-latest-yarn-${{ hashFiles('new-web/yarn.lock') }}

      - name: Install dependencies 👨🏻‍💻
        working-directory: new-web
        run: yarn install

      - name: Run linter 👀
        working-directory: new-web
        run: yarn lint

      - name: Run tests 🧪
        working-directory: new-web
        run: yarn test
