name: Open ETC Pool Friends

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  build:
    permissions:
      id-token: write # To sign.
      contents: write # To upload release assets.
      actions: read # To read workflow path.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install GoReleaser
        run: |
          curl -sfL https://install.goreleaser.com/install-goreleaser.sh | sh

      - name: Build
        run: |
          go build -o ./dist/open-etc-pool-friends

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install GoReleaser
        run: |
          curl -sfL https://install.goreleaser.com/install-goreleaser.sh | sh

      - name: Release
        run: |
          goreleaser --config .goreleaser.yml
