name: SLSA Go releaser

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  build:
    permissions:
      id-token: write # To sign.
      contents: write # To upload release assets.
      actions: read # To read workflow path.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.4.0
    with:
      go-version: 1.19
      output: ./dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install GoReleaser
        run: |
          curl -sfL https://install.goreleaser.com/install-goreleaser.sh | sh

      - name: Release
        run: |
          goreleaser --config .goreleaser.yml
