name: SLSA Go Releaser

on:
  release:
    types:
      - created

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Run SLSA Go Generator (Windows)
      uses: slsa-framework/slsa-github-generator@v1.4.0
      with:
        go-version: 1.19
        # add any other necessary configuration here

  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Run SLSA Go Generator (Linux)
      uses: slsa-framework/slsa-github-generator@v1.4.0
      with:
        go-version: 1.19
        # add any other necessary configuration here
